### ISSUE TITLE
CSE v4.1 - Missing Control Plane IP & Virtual IP Subnet parameters.

### ISSUE THREAD

**Issue by des1redState** [vmware/terraform-provider-vcd#1197]
The example `terraform.tfvars` (`examples/container-service-extension/v4.1/cluster/terraform.tfvars.example`) doesn't provide any way to configure `Control Plane IP` or `Virtual IP Subnet` parameters, which are available when creating a cluster via the web UI. These are essential for clusters which share an external IP via NAT.

Example from web UI: https://ibb.co/Y2rCmmK

**Comment by adambarreiro** [comment]
Hi @des1redState,

You are right, the example provided doesn't use these two options. To use them, you can go to [the docs](https://registry.terraform.io/providers/vmware/vcd/latest/docs/guides/container_service_extension_4_x_cluster_management), in the section where the CAPI YAML is assembled:

> To use a Control Plane IP and/or a Virtual IP Subnet, you must add the following snippets to the kind `VCDCluster` spec section. The [proposed example](https://github.com/vmware/terraform-provider-vcd/tree/main/examples/container-service-extension/v4.1/cluster) is not using this feature, so you must add a correct value for the CONTROL_PLANE_IP and/or VIRTUAL_IP_SUBNET placeholders:

```
  controlPlaneEndpoint:
    host: ${CONTROL_PLANE_IP}
    port: 6443
```

```
  loadBalancerConfigSpec:
    vipSubnet: ${VIRTUAL_IP_SUBNET}
```

You can add these two tiny snippets to the `VCDCluster` spec section of the YAML provided in the example `cluster-template-v1.25.7.yaml`, it should look like:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: VCDCluster
metadata:
  .....
spec:
  site: ...
  org: ...
  ovdc: ...
  ovdcNetwork: ....
  controlPlaneEndpoint:
    host: ${CONTROL_PLANE_IP}
    port: 6443
  loadBalancerConfigSpec:
    vipSubnet: ${VIRTUAL_IP_SUBNET}
  useAsManagementCluster: false
  userContext:
    secretRef:
      ...
```

then in the Terraform code be sure that you have something like

```
    CONTROL_PLANE_IP  = "Your desired IP here"
    VIRTUAL_IP_SUBNET = "Your desired CIDR here"
```
in the part where the template is read:

```
capvcd_yaml_rendered = templatefile("./cluster-template-v1.25.7.yaml", {
...
```

I hope this helps!
