### ISSUE TITLE
how to configure custom NTP servers for tanzu

### ISSUE THREAD

**Issue by andrzej-dobrzynski-pushgaming** [vmware/terraform-provider-vcd#1334]
Hello @adambarreiro et al

how to configure custom NTP servers for tanzu

### Terraform Version
```
% tfenv version-name
1.5.7
```

### Terraform Configuration Files
```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
spec:
  kubeadmConfigSpec:
    ntp:
      servers:
        - time.aws.com
      enabled: true
```

```
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
spec:
  template:
    spec:
      ntp:
        servers:
          - time.aws.com
        enabled: true
```

### Expected Behavior
```
% cat /etc/chrony/chrony.conf
server time.aws.com iburst
```

### Actual Behavior
```
% cat /etc/chrony/chrony.conf
server ntp.ubuntu.com iburst
```

### Steps to Reproduce
as above

### References
https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap/
```
ntp:
  servers:
    - IP_ADDRESS
  enabled: true
```

**Comment by andrzej-dobrzynski-pushgaming** [comment]
if above does not work then this does 
```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
spec:
  kubeadmConfigSpec:
    postKubeadmCommands:
    - echo "pool time.aws.com iburst prefer" >> /etc/chrony/chrony.conf && systemctl restart chrony
```
```
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
spec:
  template:
    spec:
      postKubeadmCommands:
      - echo "pool time.aws.com iburst prefer" >> /etc/chrony/chrony.conf && systemctl restart chrony
```
